# Copyright 2024 Schneider-Electric
name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    uses: myAlias/versioning/.github/workflows/ui-release.yml@v0
